// Each pair: the majority (civilian) word and a related-but-not-identical
// word for the Imposter. Mr. White gets no word at all.
export const WORD_PAIRS: [string, string][] = [
  ["Coffee", "Tea"],
  ["Ocean", "Lake"],
  ["Guitar", "Violin"],
  ["Pizza", "Pasta"],
  ["Snow", "Rain"],
  ["Lion", "Tiger"],
  ["Doctor", "Nurse"],
  ["Airplane", "Helicopter"],
  ["Chess", "Checkers"],
  ["Volcano", "Earthquake"],
  ["Bicycle", "Motorcycle"],
  ["Castle", "Palace"],
  ["Butterfly", "Moth"],
  ["Sushi", "Sashimi"],
  ["Desert", "Tundra"],
  ["Piano", "Keyboard"],
  ["Novel", "Short story"],
  ["Football", "Rugby"],
  ["Painter", "Sculptor"],
  ["River", "Stream"],
  ["Wolf", "Fox"],
  ["Diamond", "Ruby"],
  ["Spaceship", "Satellite"],
  ["Kingdom", "Empire"],
  ["Whisper", "Murmur"],
  ["Bakery", "Cafe"],
  ["Forest", "Jungle"],
  ["Thunder", "Lightning"],
  ["Marathon", "Sprint"],
  ["Sculpture", "Statue"],
  ["Lantern", "Candle"],
  ["Glacier", "Iceberg"],
  ["Trumpet", "Saxophone"],
  ["Cathedral", "Chapel"],
  ["Comet", "Meteor"],
  ["Bracelet", "Necklace"],
  ["Tornado", "Hurricane"],
  ["Falcon", "Eagle"],
  ["Village", "Town"],
  ["Perfume", "Cologne"],
  ["Puzzle", "Riddle"],
  ["Waterfall", "Rapids"],
  ["Telescope", "Microscope"],
  ["Orchard", "Vineyard"],
  ["Mermaid", "Siren"],
  ["Kayak", "Canoe"],
  ["Compass", "Map"],
  ["Igloo", "Tent"],
  ["Peacock", "Swan"],
  ["Lighthouse", "Watchtower"],
];

export function pickRandomPair(): [string, string] {
  return WORD_PAIRS[Math.floor(Math.random() * WORD_PAIRS.length)];
}
